<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>hernianrunner@gmail.com</Authors>
    <Company>herniankb</Company>
    <Copyright>hernianrunner@gmail.com</Copyright>
    <RepositoryUrl>https://github.com/hernian/MouseClickLocker</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>develop</PackageTags>
    <AssemblyVersion>1.0.1.1</AssemblyVersion>
    <ApplicationIcon>MouseClickLocker.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Form1.Designer.BAK" />
    <None Remove="LockImageBoth.png" />
    <None Remove="LockImageLeft.png" />
    <None Remove="LockImageRight.png" />
    <None Remove="MarkerForm.Designer.cs~RF11c560.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="MouseClickLocker.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\$(Platform)\$(Configuration)\MouseHookLib.dll">
      <Link>MouseHookLib.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\$(Platform)\$(Configuration)\MouseHookLib.pdb">
      <Link>MouseHookLib.pdb</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>